// scripts/vercel-build.js
// Called during `vercel build` or `npm run vercel-build`.
// Generates env.js from Vercel Environment Variables so the app can use
// real API keys in production without committing them to git.

const fs = require('fs');
const path = require('path');

const aiKey = process.env.GOOGLE_AI_STUDIO_KEY || 'YOUR_GOOGLE_AI_STUDIO_KEY';
const mapsKey = process.env.GOOGLE_MAPS_KEY || 'YOUR_GOOGLE_MAPS_KEY';

const content = `// env.js — Auto-generated by Vercel build.
// Do NOT edit manually — set GOOGLE_AI_STUDIO_KEY and GOOGLE_MAPS_KEY
// in your Vercel project's Environment Variables instead.
window.__CIVICFIX_ENV__ = {
  GOOGLE_AI_STUDIO_KEY: ${JSON.stringify(aiKey)},
  GOOGLE_MAPS_KEY: ${JSON.stringify(mapsKey)}
};
`;

const dest = path.join(__dirname, '..', 'env.js');
fs.writeFileSync(dest, content, 'utf-8');
console.log('Generated env.js from Vercel environment variables.');
console.log('  GOOGLE_AI_STUDIO_KEY:', aiKey === 'YOUR_GOOGLE_AI_STUDIO_KEY' ? '(placeholder)' : '(set)');
console.log('  GOOGLE_MAPS_KEY:', mapsKey === 'YOUR_GOOGLE_MAPS_KEY' ? '(placeholder)' : '(set)');
